#!/usr/bin/env node

/**
 * [nct : node cli tools]
 * @author: xgqfrms
 * @date: 2017-06-12
 */

const nct = require('./libs');

const username = process.argv[2] || `xgqfrms-GitHub`;
const repo = process.argv[3] || `Node-CLI-Tools`;

nct(username, repo);
